// frontend/src/pages/SavedPlans.jsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";

export default function SavedPlans({ onChange }) {
  const [plans, setPlans] = useState(null);
  const load = () => api.plans().then(setPlans);
  useEffect(() => { load(); }, []);

  async function remove(id) {
    await api.deletePlan(id);
    await load();
    onChange?.();
  }

  if (!plans) return <div>Loading…</div>;
  return (
    <>
      <h1>Saved Plans</h1>
      {!plans.length && <div className="card">No plans yet. <Link to="/planner">Create one</Link>.</div>}
      <div className="kanban-board">
        {plans.map((p, i) => {
          const color = ["blue", "orange", "green"][i % 3];
          return (
            <div key={p.id} className={`kanban-col ${color}`}>
              <div className="kanban-header">
                <h3>{p.name}</h3>
                <span className="sub">{p.total_credits} credits • {p.courses.length} courses</span>
                <button className="kanban-del" onClick={() => remove(p.id)} title="Delete Plan">✕</button>
              </div>
              <div className="kanban-body">
                {p.courses.map((c, idx) => (
                  <div key={c.id} className="k-card">
                    <div className="k-card-index">{idx + 1}</div>
                    <div className="k-card-content">
                      <div className="k-card-title">{c.name}</div>
                      <div className="k-card-code">{c.id}</div>
                    </div>
                    <div className="k-card-credits">{c.credits}</div>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
}

// frontend/src/pages/SavedPlans.vue
<template>
  <h1>Saved Plans</h1>
  <div v-if="!plans" class="muted">Loading…</div>
  <template v-else>
    <div v-if="!plans.length" class="card">No plans yet. <RouterLink to="/planner">Create one</RouterLink>.</div>
    <div v-for="p in plans" :key="p.id" class="plan-block">
      <div class="row between">
        <div>
          <h3 class="plan-name">{{ p.name }}</h3>
          <span class="muted">{{ p.terms.length }} terms · {{ p.course_count }} courses · {{ p.total_credits }} credits</span>
        </div>
        <div class="row gap-s">
          <RouterLink :to="`/planner/${p.id}`" class="btn"><Pencil :size="16" /> Edit</RouterLink>
          <button class="btn danger" @click="remove(p.id)"><Trash2 :size="16" /> Delete</button>
        </div>
      </div>
      <PlanTerms :terms="p.terms" />
    </div>
  </template>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { RouterLink } from "vue-router";
import { Trash2, Pencil } from "lucide-vue-next";
import { api } from "../api";
import PlanTerms from "./PlanTerms.vue";

const emit = defineEmits(["changed"]);
const plans = ref(null);
async function load() { plans.value = await api.plans(); }
onMounted(load);

async function remove(id) {
  if (!confirm("Delete this plan?")) return;
  await api.deletePlan(id);
  await load();
  emit("changed");
}
</script>
