// frontend/src/App.jsx
import { useCallback, useEffect, useState } from "react";
import { NavLink, Route, Routes } from "react-router-dom";
import { api } from "./api";
import Dashboard from "./pages/Dashboard.jsx";
import Planner from "./pages/Planner.jsx";
import SavedPlans from "./pages/SavedPlans.jsx";
import Recommendations from "./pages/Recommendations.jsx";
import CreditTracker from "./pages/CreditTracker.jsx";

const NAV = [
  ["MAIN", [["/", "Dashboard"]]],
  ["FOUNDATION", [["/recommendations", "Recommendations"]]],
  ["PLANNER", [["/planner", "Course Planner"], ["/plans", "Saved Plans"]]],
  ["PROGRESS", [["/tracker", "Credit Progress Tracker"]]],
];

export default function App() {
  const [student, setStudent] = useState(null);
  const [error, setError] = useState("");
  const [isAuth, setIsAuth] = useState(!!localStorage.getItem("token"));
  const [email, setEmail] = useState("demo@example.com");
  const [password, setPassword] = useState("password123");

  const refresh = useCallback(
    () => {
      if (!isAuth) return;
      api.student().then(setStudent).catch((e) => {
        if (e.message.includes("Could not validate credentials")) setIsAuth(false);
        else setError(e.message);
      })
    },
    [isAuth]
  );
  useEffect(() => { refresh(); }, [refresh]);

  async function handleLogin(e) {
    e.preventDefault();
    try {
      await api.login(email, password);
      setIsAuth(true);
      setError("");
    } catch (err) {
      setError("Login failed. Check credentials.");
    }
  }

  function handleLogout() {
    api.logout();
    setIsAuth(false);
    setStudent(null);
  }

  if (!isAuth) return (
    <div className="page" style={{ maxWidth: 400, margin: "100px auto" }}>
      <form className="card" onSubmit={handleLogin}>
        <h3>Login</h3>
        {error && <div className="alert error">{error}</div>}
        <div style={{ marginBottom: 16 }}>
          <label className="muted small">Email</label>
          <input className="input" type="email" value={email} onChange={e => setEmail(e.target.value)} required />
        </div>
        <div style={{ marginBottom: 16 }}>
          <label className="muted small">Password</label>
          <input className="input" type="password" value={password} onChange={e => setPassword(e.target.value)} required />
        </div>
        <button className="btn primary wide" type="submit">Sign In</button>
      </form>
    </div>
  );

  if (error) return <div className="page"><div className="alert error">API error: {error}. Is the backend running on :8000?</div></div>;
  if (!student) return <div className="page">Loading…</div>;

  return (
    <div className="layout">
      <aside className="sidebar">
        {NAV.map(([section, links]) => (
          <div key={section}>
            <div className="nav-section">{section}</div>
            {links.map(([to, label]) => (
              <NavLink key={to} to={to} end={to === "/"} className="nav-link">{label}</NavLink>
            ))}
          </div>
        ))}
        <div className="beta">
          <b>Beta:</b> This app is under beta testing. If you face any issues, please report them.
        </div>
        <div style={{ marginTop: 24 }}>
          <button className="btn danger wide" onClick={handleLogout}>Logout</button>
        </div>
      </aside>
      <main className="page">
        <Routes>
          <Route path="/" element={<Dashboard student={student} />} />
          <Route path="/planner" element={<Planner student={student} onSaved={refresh} />} />
          <Route path="/plans" element={<SavedPlans onChange={refresh} />} />
          <Route path="/recommendations" element={<Recommendations />} />
          <Route path="/tracker" element={<CreditTracker onChange={refresh} />} />
        </Routes>
      </main>
    </div>
  );
}

// frontend/src/App.vue
<template>
  <div v-if="error" class="page"><div class="alert error">Could not reach the API: {{ error }}</div></div>
  <div v-else-if="!student" class="page muted">Loading…</div>
  <div v-else class="layout">
    <aside class="sidebar">
      <div v-for="section in NAV" :key="section.title">
        <div class="nav-section">{{ section.title }}</div>
        <RouterLink v-for="l in section.links" :key="l.to" :to="l.to" class="nav-link"
                    :class="{ active: isActive(l.to) }">
          <component :is="l.icon" :size="18" /> {{ l.label }}
        </RouterLink>
      </div>
      <div class="beta">
        <div><b>Beta:</b> This app is under beta testing. If you are facing any issues, please let the developer know.</div>
        <div class="btn report"><Bug :size="16" /> Report an Issue</div>
      </div>
    </aside>
    <main class="page">
      <RouterView :student="student" @changed="refresh" />
    </main>
  </div>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { RouterLink, RouterView, useRoute } from "vue-router";
import { Bug, CalendarCheck, Compass, Layers, LayoutGrid, LineChart, TrendingUp } from "lucide-vue-next";
import { api } from "./api";

const NAV = [
  { title: "MAIN", links: [{ to: "/", label: "Dashboard", icon: LayoutGrid }] },
  { title: "FOUNDATION", links: [
    { to: "/recommendations", label: "Recommendations", icon: Compass },
    { to: "/insights", label: "Course Insights", icon: LineChart },
  ] },
  { title: "PLANNER", links: [
    { to: "/planner", label: "Course Planner", icon: CalendarCheck },
    { to: "/plans", label: "Saved Plans", icon: Layers },
  ] },
  { title: "PROGRESS", links: [{ to: "/tracker", label: "Credit Progress Tracker", icon: TrendingUp }] },
];

const route = useRoute();
const student = ref(null);
const error = ref("");

function isActive(to) {
  return to === "/" ? route.path === "/" : route.path === to;
}

async function refresh() {
  try { student.value = await api.student(); }
  catch (e) { error.value = e.message; }
}
onMounted(refresh);
</script>
